# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Claibonia!
email: mclaibourn@virginia.edu
description: >
  A test web page on GitHub!
logo: "/assets/images/logo.jpg"
baseurl: "/Jekyll-AMP" # the subpath of your site, e.g. /blog
url: "https://mclaibourn.github.io" # the base hostname & protocol for your site
paginate:	5 # The number of posts to show per page on your homepage

name: 'Michele Claibourn'
bio: >
  Looking for a Web that Works
author_image: "/assets/images/author.jpg"
twitter_username: mclaibourn
github_username:  mclaibourn

# Google Analytics
analytics_id: ""

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

gems:
  - jekyll-paginate

prose:
  siteurl: 'https://mclaibourn.github.io/Jekyll-AMP'
    ignore:
    - .gitignore
    - "CNAME"
    - Gemfile
    - Gemfile.lock
    - README.md
    - index.md
    - _config.yml
    - /_posts/testpost
  media: "images"
  metadata:
    _posts:
      - name: "published"
        field:
          element: 'hidden'
          value: false
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "categories"
        field:
          element: "multiselect"
          label: "Add Categories"
          placeholder: "Add Categories"
          alterable: true
      - name: "date"
        field:
          element: "text"
          label: "Date"
          value: "CURRENT_DATETIME"
      - name: "title"
        field:
          element: "text"
          label: "Post title"
          placeholder: "Title"
          alterable: true
      - name: "excerpt"
        field:
          element: "textarea"
          label: "Excerpt"
          help: "Fill this in to provide an excerpt"
      - name: "excerpt_separator"
        field:
          element: "text"
          label: "Excerpt Separator"
          help: "If this is filled in, the entire post will be displayed up to the seperator placeholder."
          placeholder: "Replace with something like: <!--more-->"
